import { useEffect, useState } from "react";
import { Edit3, Plus, Save, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import Loader from "../components/admin/Loader";
import { createOffer, deleteOffer, getOffers, updateOffer } from "../services/api";

const blank={title:"",description:"",couponCode:"",discountType:"text",discountValue:0,badge:"Special Offer",buttonLabel:"Claim Offer",buttonUrl:"/contact/",displayType:"bar",pages:["all"],startAt:"",endAt:"",isActive:true,priority:0,terms:""};
const input="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-cyan-400";
const dateValue=v=>{if(!v)return "";const d=new Date(v);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};
const toIso=v=>v?new Date(v).toISOString():null;
export default function Offers(){
 const [items,setItems]=useState(null),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
 const load=()=>getOffers().then(d=>setItems(d.offers||[])).catch(e=>toast.error(e.message));
 useEffect(()=>{ load(); },[]);
 const field=(k,v)=>setForm(f=>({...f,[k]:v}));
 const start=(offer=null)=>{setEditing(offer?offer._id:null);setForm(offer?{...blank,...offer,startAt:dateValue(offer.startAt),endAt:dateValue(offer.endAt),pages:offer.pages||["all"]}:blank);setOpen(true)};
 const submit=async e=>{e.preventDefault();setSaving(true);const payload={...form,startAt:toIso(form.startAt),endAt:toIso(form.endAt)};try{editing?await updateOffer(editing,payload):await createOffer(payload);toast.success(editing?"Offer updated":"Offer created");setOpen(false);load()}catch(err){toast.error(err.message)}finally{setSaving(false)}};
 const remove=async id=>{if(!window.confirm("Delete this offer?"))return;try{await deleteOffer(id);toast.success("Offer deleted");load()}catch(e){toast.error(e.message)}};
 if(!items)return <Loader/>;
 return <div className="max-w-6xl space-y-6"><div className="flex flex-wrap items-center justify-between gap-4 rounded-3xl border border-white/10 bg-slate-900/80 p-6"><div><p className="text-xs uppercase tracking-[.3em] text-cyan-300">Marketing</p><h2 className="text-2xl font-semibold">Offer manager</h2><p className="mt-2 text-sm text-slate-400">Schedule announcement bars, banners and popups page-wise.</p></div><button onClick={()=>start()} className="flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-3 font-semibold text-slate-950"><Plus size={18}/>New offer</button></div>
 <div className="grid gap-4 lg:grid-cols-2">{items.map(o=><article key={o._id} className="rounded-3xl border border-white/10 bg-slate-900/80 p-5"><div className="flex items-start justify-between gap-3"><div><span className={`rounded-full px-3 py-1 text-xs ${o.isActive?"bg-emerald-500/15 text-emerald-300":"bg-slate-700 text-slate-400"}`}>{o.isActive?"Active":"Inactive"}</span><h3 className="mt-3 text-xl font-semibold">{o.title}</h3><p className="mt-2 text-sm text-slate-400">{o.description||"No description"}</p></div><div className="flex gap-2"><button onClick={()=>start(o)} className="rounded-lg bg-white/5 p-2 text-cyan-300"><Edit3 size={17}/></button><button onClick={()=>remove(o._id)} className="rounded-lg bg-rose-500/10 p-2 text-rose-300"><Trash2 size={17}/></button></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-400"><span className="rounded-lg bg-slate-950 px-3 py-2">{o.displayType}</span>{o.couponCode&&<span className="rounded-lg bg-slate-950 px-3 py-2">Code: {o.couponCode}</span>}<span className="rounded-lg bg-slate-950 px-3 py-2">Pages: {(o.pages||[]).join(", ")}</span></div></article>)}{!items.length&&<p className="rounded-3xl border border-dashed border-white/10 p-10 text-center text-slate-400">No offers yet.</p>}</div>
 {open&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/80 p-4 backdrop-blur"><form onSubmit={submit} className="mx-auto my-8 max-w-3xl space-y-5 rounded-3xl border border-white/10 bg-slate-900 p-6"><div className="flex justify-between"><h3 className="text-xl font-semibold">{editing?"Edit offer":"Create offer"}</h3><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Offer title" value={form.title} set={v=>field("title",v)} required/><Field label="Badge" value={form.badge} set={v=>field("badge",v)}/><Field label="Description" value={form.description} set={v=>field("description",v)} wide/><Field label="Coupon code" value={form.couponCode} set={v=>field("couponCode",v)}/><label className="text-sm text-slate-300">Discount type<select className={`mt-2 ${input}`} value={form.discountType} onChange={e=>field("discountType",e.target.value)}><option value="text">Text only</option><option value="percentage">Percentage</option><option value="flat">Flat amount</option></select></label><Field label="Discount value" type="number" value={form.discountValue} set={v=>field("discountValue",v)}/><label className="text-sm text-slate-300">Display<select className={`mt-2 ${input}`} value={form.displayType} onChange={e=>field("displayType",e.target.value)}><option value="bar">Top bar</option><option value="banner">Banner</option><option value="popup">Popup</option></select></label><Field label="Button label" value={form.buttonLabel} set={v=>field("buttonLabel",v)}/><Field label="Button URL" value={form.buttonUrl} set={v=>field("buttonUrl",v)}/><Field label="Pages (all or /services, /blogs)" value={form.pages.join(", ")} set={v=>field("pages",v.split(",").map(x=>x.trim()).filter(Boolean))}/><Field label="Starts" type="datetime-local" value={form.startAt} set={v=>field("startAt",v)}/><Field label="Ends" type="datetime-local" value={form.endAt} set={v=>field("endAt",v)}/><Field label="Priority" type="number" value={form.priority} set={v=>field("priority",v)}/><Field label="Terms" value={form.terms} set={v=>field("terms",v)} wide/></div><label className="flex gap-3"><input type="checkbox" checked={form.isActive} onChange={e=>field("isActive",e.target.checked)}/> Active and visible</label><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950"><Save size={17}/>{saving?"Saving...":"Save offer"}</button></form></div>}
 </div>;
}
function Field({label,value,set,type="text",wide,required}){return <label className={`text-sm text-slate-300 ${wide?"sm:col-span-2":""}`}>{label}<input required={required} type={type} className={`mt-2 ${input}`} value={value??""} onChange={e=>set(e.target.value)}/></label>}
