import { useEffect, useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import Loader from "../components/admin/Loader";
import { getSiteSettings, updateSiteSettings } from "../services/api";

const defaults = { siteName: "Digital Pintu Solutions", siteUrl: "https://www.digitalpintu.com", defaultTitle: "", titleTemplate: "%s | Digital Pintu Solutions", defaultDescription: "", businessDescription: "", defaultOgImage: "", twitterHandle: "", organizationLogo: "", organizationType: "ProfessionalService", robotsIndex: true, robotsFollow: true, googleVerification: "", bingVerification: "", pageSeo: {}, imageAltText: {} };
const field = "mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-cyan-400";
const blankPage = { path: "/", title: "", description: "", keywords: "", canonicalUrl: "", ogTitle: "", ogDescription: "", ogImage: "", noIndex: false, breadcrumbName: "", faqs: [] };

export default function SeoSettings() {
  const [all, setAll] = useState(null); const [seo, setSeo] = useState(defaults); const [saving, setSaving] = useState(false);
  useEffect(() => { getSiteSettings().then(({ settings }) => { setAll(settings); setSeo({ ...defaults, ...(settings.seoSettings || {}) }); }).catch((e) => toast.error(e.message)); }, []);
  const set = (key, value) => setSeo((current) => ({ ...current, [key]: value }));
  const pages = Object.entries(seo.pageSeo || {});
  const updatePage = (oldPath, next) => setSeo((current) => { const pageSeo = { ...current.pageSeo }; delete pageSeo[oldPath]; pageSeo[next.path || oldPath] = next; return { ...current, pageSeo }; });
  const save = async (e) => { e.preventDefault(); setSaving(true); try { const data = await updateSiteSettings({ ...all, seoSettings: seo }); setAll(data.settings); setSeo({ ...defaults, ...data.settings.seoSettings }); toast.success("SEO settings saved"); } catch (error) { toast.error(error.message); } finally { setSaving(false); } };
  if (!all) return <Loader />;
  return <form onSubmit={save} className="max-w-5xl space-y-6"><header className="rounded-3xl border border-white/10 bg-slate-900/80 p-5"><p className="text-xs uppercase tracking-[.3em] text-cyan-300">Search visibility</p><h2 className="mt-1 text-2xl font-semibold">SEO control center</h2><p className="mt-2 text-sm text-slate-400">Manage global metadata, page SEO, social previews, schema, FAQs, breadcrumbs, crawl settings and image alt text.</p></header>
    <Section title="Global SEO"><Grid>{[["siteName","Site name"],["siteUrl","Website URL"],["defaultTitle","Default meta title"],["titleTemplate","Title template"],["defaultOgImage","Default OG image URL"],["twitterHandle","Twitter handle"],["organizationLogo","Organization logo URL"],["googleVerification","Google verification code"],["bingVerification","Bing verification code"]].map(([key,label]) => <Field key={key} label={label} value={seo[key]} onChange={(v) => set(key,v)} />)}<label className="text-sm sm:col-span-2">Default meta description<textarea rows="3" className={field} value={seo.defaultDescription} onChange={(e) => set("defaultDescription",e.target.value)} /></label></Grid><div className="flex gap-6 text-sm"><Check label="Allow indexing" checked={seo.robotsIndex} onChange={(v) => set("robotsIndex",v)} /><Check label="Allow link following" checked={seo.robotsFollow} onChange={(v) => set("robotsFollow",v)} /></div></Section>
    <Section title="Page SEO"><button type="button" onClick={() => updatePage(`/new-${Date.now()}`,{...blankPage,path:`/new-${Date.now()}`})} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500/15 px-3 py-2 text-cyan-300"><Plus size={16}/>Add page SEO</button>{pages.map(([path,page]) => <PageEditor key={path} path={path} page={page} update={(next) => updatePage(path,next)} remove={() => setSeo((current) => { const pageSeo={...current.pageSeo}; delete pageSeo[path]; return {...current,pageSeo}; })} />)}</Section>
    <Section title="Image alt text"><p className="text-sm text-slate-400">Use an image key such as <code>hero-dashboard</code>, <code>site-logo</code>, or an image URL/filename.</p>{Object.entries(seo.imageAltText || {}).map(([key,value]) => <div key={key} className="grid gap-3 sm:grid-cols-[1fr_2fr_auto]"><input className={field} value={key} readOnly/><input className={field} value={value} onChange={(e)=>set("imageAltText",{...seo.imageAltText,[key]:e.target.value})}/><button type="button" onClick={()=>{const next={...seo.imageAltText};delete next[key];set("imageAltText",next)}} className="mt-2 p-3 text-rose-300"><Trash2 size={17}/></button></div>)}<button type="button" onClick={()=>set("imageAltText",{...seo.imageAltText,[`image-${Date.now()}`]:""})} className="text-sm text-cyan-300">+ Add image alt text</button></Section>
    <button disabled={saving} className="sticky bottom-5 inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950"><Save size={17}/>{saving?"Saving...":"Save SEO settings"}</button>
  </form>;
}
function PageEditor({path,page,update,remove}) { const set=(key,value)=>update({...page,path:page.path||path,[key]:value}); const faq=(i,key,value)=>set("faqs",(page.faqs||[]).map((item,index)=>index===i?{...item,[key]:value}:item)); return <div className="space-y-4 rounded-2xl border border-white/10 bg-slate-950/50 p-4"><div className="flex justify-between"><b>{page.path||path}</b><button type="button" onClick={remove} className="text-rose-300"><Trash2 size={17}/></button></div><Grid>{[["path","Route path"],["title","Meta title"],["description","Meta description"],["canonicalUrl","Canonical URL"],["ogTitle","Open Graph title"],["ogDescription","Open Graph description"],["ogImage","Open Graph image URL"],["breadcrumbName","Breadcrumb label"]].map(([key,label])=><Field key={key} label={label} value={page[key]||""} onChange={(v)=>set(key,v)}/>)}</Grid><Check label="Noindex this page" checked={Boolean(page.noIndex)} onChange={(v)=>set("noIndex",v)}/><div><b className="text-sm">FAQs</b>{(page.faqs||[]).map((item,i)=><div key={i} className="mt-3 grid gap-3 sm:grid-cols-[1fr_2fr_auto]"><input className={field} placeholder="Question" value={item.question} onChange={(e)=>faq(i,"question",e.target.value)}/><textarea className={field} placeholder="Answer" value={item.answer} onChange={(e)=>faq(i,"answer",e.target.value)}/><button type="button" onClick={()=>set("faqs",page.faqs.filter((_,x)=>x!==i))} className="mt-2 text-rose-300"><Trash2 size={17}/></button></div>)}<button type="button" onClick={()=>set("faqs",[...(page.faqs||[]),{question:"",answer:""}])} className="mt-3 text-sm text-cyan-300">+ Add FAQ</button></div></div> }
function Section({title,children}){return <section className="space-y-5 rounded-3xl border border-white/10 bg-slate-900/80 p-5"><h3 className="text-lg font-semibold">{title}</h3>{children}</section>} function Grid({children}){return <div className="grid gap-4 sm:grid-cols-2">{children}</div>} function Field({label,value,onChange}){return <label className="text-sm">{label}<input className={field} value={value||""} onChange={(e)=>onChange(e.target.value)}/></label>} function Check({label,checked,onChange}){return <label className="flex items-center gap-2"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/>{label}</label>}
