import { useEffect, useState } from "react";
import { Palette, Save } from "lucide-react";
import { toast } from "sonner";
import Loader from "../components/admin/Loader";
import { getSiteSettings, updateSiteSettings } from "../services/api";

const defaults = { mode:"dark", primaryColor:"#22d3ee", secondaryColor:"#3b82f6", accentColor:"#8b5cf6", backgroundColor:"#070b14", surfaceColor:"#0b1020", textColor:"#ffffff", mutedTextColor:"#94a3b8", fontFamily:"Inter", borderRadius:16, buttonStyle:"rounded", animationEnabled:true };
const fields = [["primaryColor","Primary"],["secondaryColor","Secondary"],["accentColor","Accent"],["backgroundColor","Background"],["surfaceColor","Cards / Surface"],["textColor","Main text"],["mutedTextColor","Muted text"]];

export default function ThemeSettings(){
  const [settings,setSettings]=useState(null); const [theme,setTheme]=useState(defaults); const [saving,setSaving]=useState(false);
  useEffect(()=>{getSiteSettings().then(({settings:s})=>{setSettings(s);setTheme({...defaults,...s.themeSettings});}).catch(e=>toast.error(e.message));},[]);
  const set=(key,value)=>setTheme(t=>({...t,[key]:value}));
  const save=async(e)=>{e.preventDefault();setSaving(true);try{const data=await updateSiteSettings({...settings,themeSettings:theme});setSettings(data.settings);toast.success("Theme published");}catch(err){toast.error(err.message)}finally{setSaving(false)}};
  if(!settings)return <Loader/>;
  return <form onSubmit={save} className="max-w-5xl space-y-6"><div className="rounded-3xl border border-white/10 bg-slate-900/80 p-6"><div className="flex items-center gap-3"><Palette className="text-cyan-300"/><div><p className="text-xs uppercase tracking-[.3em] text-cyan-300">Appearance</p><h2 className="text-2xl font-semibold">Overall website theme</h2></div></div><p className="mt-3 text-sm text-slate-400">Colors, typography, corners and motion are applied across the public website.</p></div>
  <section className="rounded-3xl border border-white/10 bg-slate-900/80 p-6"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([key,label])=><label key={key} className="text-sm text-slate-300">{label}<div className="mt-2 flex rounded-xl border border-white/10 bg-slate-950 p-2"><input type="color" value={theme[key]} onChange={e=>set(key,e.target.value)} className="h-10 w-12 bg-transparent"/><input value={theme[key]} onChange={e=>set(key,e.target.value)} className="min-w-0 flex-1 bg-transparent px-2 outline-none"/></div></label>)}</div></section>
  <section className="grid gap-5 rounded-3xl border border-white/10 bg-slate-900/80 p-6 sm:grid-cols-2"><label className="text-sm text-slate-300">Theme mode<select value={theme.mode} onChange={e=>set("mode",e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 p-3"><option value="dark">Dark</option><option value="light">Light</option></select></label><label className="text-sm text-slate-300">Font<select value={theme.fontFamily} onChange={e=>set("fontFamily",e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 p-3"><option>Inter</option><option>Poppins</option><option>Roboto</option><option>Montserrat</option><option>Georgia</option></select></label><label className="text-sm text-slate-300">Corner radius: {theme.borderRadius}px<input type="range" min="0" max="32" value={theme.borderRadius} onChange={e=>set("borderRadius",Number(e.target.value))} className="mt-3 w-full"/></label><label className="flex items-center gap-3 self-end rounded-xl border border-white/10 p-3"><input type="checkbox" checked={theme.animationEnabled} onChange={e=>set("animationEnabled",e.target.checked)}/> Enable website animations</label></section>
  <div className="rounded-3xl p-8" style={{background:theme.backgroundColor,color:theme.textColor,fontFamily:theme.fontFamily}}><p style={{color:theme.primaryColor}}>Live preview</p><h3 className="mt-2 text-3xl font-bold">Digital Pintu Theme</h3><button type="button" className="mt-5 px-5 py-3 font-semibold text-white" style={{background:`linear-gradient(90deg,${theme.primaryColor},${theme.secondaryColor})`,borderRadius:theme.borderRadius}}>Preview button</button></div>
  <button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950"><Save size={17}/>{saving?"Publishing...":"Publish theme"}</button></form>;
}
