import { useEffect, useState } from 'react';
import { Activity, Users } from 'lucide-react';
import Loader from '../components/admin/Loader';
import Table from '../components/admin/Table';
import StatsCard from '../components/admin/StatsCard';
import { getVisitorTracker } from '../services/api';
const date = v => v ? new Date(v).toLocaleString() : '—';
export default function UserTracker() {
    const [data, setData] = useState(null), [loading, setLoading] = useState(true); useEffect(() => { getVisitorTracker().then(setData).catch(() => setData({ stats: { total: 0, online: 0, today: 0 }, visitors: [] })).finally(() => setLoading(false)) }, []); if (loading) return <Loader />; return <div className="space-y-6"><div><p className="text-sm uppercase tracking-[.3em] text-cyan-300">User Tracker</p><h2 className="text-2xl font-semibold text-white">Visitor activity</h2></div><div className="grid gap-4 md:grid-cols-3"><StatsCard title="Total Visitors" value={data?.stats?.total || 0} subtitle="Recorded visitors" icon={<Users size={18} />} /><StatsCard title="Online Visitors" value={data?.stats?.online || 0} subtitle="Active in last 5 minutes" icon={<Activity size={18} />} /><StatsCard title="Today's Visitors" value={data?.stats?.today || 0} subtitle="First visits today" icon={<Users size={18} />} /></div><Table headers={['Name', 'Email', 'Guest/User', 'IP', 'Browser', 'Device', 'Current Page', 'Last Activity', 'Visit Time']}>{(data?.visitors || []).map(v => <tr key={v._id}><td className="px-4 py-3 font-medium">{v.userName || 'Guest'}</td><td className="px-4 py-3 text-slate-400">{v.email || '—'}</td><td className="px-4 py-3">{v.loggedIn ? 'User' : 'Guest'}</td><td className="px-4 py-3 text-slate-400">{v.ipAddress}</td><td className="px-4 py-3">{v.browser}</td><td className="px-4 py-3">{v.device}</td><td className="px-4 py-3">{v.currentPage}</td><td className="px-4 py-3 text-slate-400">{date(v.lastActivity)}</td><td className="px-4 py-3 text-slate-400">{date(v.visitTime)}</td></tr>)}</Table>{!data?.visitors?.length && <p className="rounded-3xl border border-dashed border-white/15 p-10 text-center text-slate-400">No visitors tracked yet.</p>}</div>
}
